"""Expanded child job workflow from Pentaho: Load_Finance_Data.kjb

Source: C:/Users/Prateek.Kotian/Desktop/Pentaho/Retail & E-commerce/Retail_ETL_Project/jobs/finance/Load_Finance_Data.kjb
Full entry/hop graph — not a stub. TRANS entries call retail transformation modules.
"""

from __future__ import annotations

import importlib
import logging
from pathlib import Path
from typing import Any, Mapping

from pentaho_migration.common.databricks_opt import (
    apply_spark_runtime_hints,
    get_logger,
    log_event,
    timed,
)
from pentaho_migration.job_engine import (
    EntryResult,
    JobEntry,
    JobExecutionError,
    JobHop,
    JobRuntime,
    substitute_variables,
)

logger = logging.getLogger("Master_ETL.children.load_finance_data")
_LOG = get_logger("Master_ETL.children.load_finance_data")

JOB_NAME = 'Load_Finance_Data'
SOURCE_KJB = 'Load_Finance_Data.kjb'
EXPANDED = True

ENTRY_DEFS = [{'attributes': {'DayOfMonth': '1',
                 'description': 'Job entry point',
                 'draw': 'Y',
                 'dummy': 'N',
                 'hour': '12',
                 'intervalMinutes': '60',
                 'intervalSeconds': '0',
                 'minutes': '0',
                 'nr': '0',
                 'parallel': 'N',
                 'repeat': 'N',
                 'schedulerType': '0',
                 'weekDay': '1',
                 'xloc': '48',
                 'yloc': '80'},
  'entry_type': 'SPECIAL',
  'filename': '',
  'is_start': True,
  'jobname': '',
  'name': 'Start',
  'transname': ''},
 {'attributes': {'description': 'Structured execution log',
                 'displayHeader': 'Y',
                 'draw': 'Y',
                 'limitRows': 'N',
                 'limitRowsNumber': '0',
                 'loglevel': 'BASIC',
                 'logmessage': 'AUDIT | EVENT=JOB_STARTED | JOB=Load_Finance_Data | '
                               'RUN_ID=${RUN_ID} | ROWS_PROCESSED=PENDING',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '200',
                 'yloc': '80'},
  'entry_type': 'WRITE_TO_LOG',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Log Job Started',
  'transname': ''},
 {'attributes': {'description': 'Initialize / refresh variables',
                 'draw': 'Y',
                 'file_variable_type': 'JVM',
                 'nr': '0',
                 'parallel': 'N',
                 'replace': 'Y',
                 'xloc': '360',
                 'yloc': '80'},
  'entry_type': 'SET_VARIABLES',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Ensure Path Variables',
  'transname': ''},
 {'attributes': {'description': 'Ensure folder exists: ${REJECT_MODULE_PATH}',
                 'draw': 'Y',
                 'fail_of_folder_exists': 'N',
                 'foldername': '${REJECT_MODULE_PATH}',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '520',
                 'yloc': '80'},
  'entry_type': 'CREATE_FOLDER',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Create Module Reject Folder',
  'transname': ''},
 {'attributes': {'description': 'Ensure folder exists: ${LOG_MODULE_PATH}',
                 'draw': 'Y',
                 'fail_of_folder_exists': 'N',
                 'foldername': '${LOG_MODULE_PATH}',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '680',
                 'yloc': '80'},
  'entry_type': 'CREATE_FOLDER',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Create Module Log Folder',
  'transname': ''},
 {'attributes': {'description': 'Gate on required source file',
                 'draw': 'Y',
                 'filename': '${DATASET_PATH}/payments.csv',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '840',
                 'yloc': '80'},
  'entry_type': 'FILE_EXISTS',
  'filename': '${DATASET_PATH}/payments.csv',
  'is_start': False,
  'jobname': '',
  'name': 'File Exists payments.csv',
  'transname': ''},
 {'attributes': {'description': 'Gate on required source file',
                 'draw': 'Y',
                 'filename': '${DATASET_PATH}/shipments.csv',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '1000',
                 'yloc': '80'},
  'entry_type': 'FILE_EXISTS',
  'filename': '${DATASET_PATH}/shipments.csv',
  'is_start': False,
  'jobname': '',
  'name': 'File Exists shipments.csv',
  'transname': ''},
 {'attributes': {'description': 'Gate on required source file',
                 'draw': 'Y',
                 'filename': '${DATASET_PATH}/exchange_rates.csv',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '1160',
                 'yloc': '80'},
  'entry_type': 'FILE_EXISTS',
  'filename': '${DATASET_PATH}/exchange_rates.csv',
  'is_start': False,
  'jobname': '',
  'name': 'File Exists exchange_rates.csv',
  'transname': ''},
 {'attributes': {'addfiletoresult': 'N',
                 'afterunzip': '0',
                 'createfolder': 'Y',
                 'description': 'Unzip seed/reference packages if present',
                 'draw': 'Y',
                 'iffileexists': '0',
                 'isfromprevious': 'N',
                 'nr': '0',
                 'parallel': 'N',
                 'rootzip': 'N',
                 'sourcedirectory': '${OUTPUT_PATH}/staging/temp',
                 'wildcardsource': '.*\\.csv',
                 'xloc': '1320',
                 'yloc': '80',
                 'zipfilename': '${DATASET_PATH}/finance_ref_optional.zip'},
  'entry_type': 'UNZIP_FILE',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Unzip Reference Package Optional',
  'transname': ''},
 {'attributes': {'DayOfMonth': '1',
                 'description': 'Bypass when optional zip is absent',
                 'draw': 'Y',
                 'dummy': 'Y',
                 'hour': '12',
                 'intervalMinutes': '60',
                 'intervalSeconds': '0',
                 'minutes': '0',
                 'nr': '0',
                 'parallel': 'N',
                 'repeat': 'N',
                 'schedulerType': '0',
                 'weekDay': '1',
                 'xloc': '1480',
                 'yloc': '80'},
  'entry_type': 'SPECIAL',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Continue After Optional Unzip',
  'transname': ''},
 {'attributes': {'addFilenameResult': 'N',
                 'checkCycleTime': '5',
                 'description': 'SLA wait for source drop',
                 'draw': 'Y',
                 'fileSizeCheck': 'N',
                 'filename': '${DATASET_PATH}/payments.csv',
                 'maximumTimeout': '30',
                 'nr': '0',
                 'parallel': 'N',
                 'successOnTimeout': 'Y',
                 'xloc': '1640',
                 'yloc': '80'},
  'entry_type': 'WAIT_FOR_FILE',
  'filename': '${DATASET_PATH}/payments.csv',
  'is_start': False,
  'jobname': '',
  'name': 'Wait For Primary Source',
  'transname': ''},
 {'attributes': {'description': 'Structured execution log',
                 'displayHeader': 'Y',
                 'draw': 'Y',
                 'limitRows': 'N',
                 'limitRowsNumber': '0',
                 'loglevel': 'BASIC',
                 'logmessage': 'AUDIT | EVENT=SOURCES_READY | JOB=Load_Finance_Data | '
                               'DATASET_PATH=${DATASET_PATH}',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '1800',
                 'yloc': '80'},
  'entry_type': 'WRITE_TO_LOG',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Log Sources Ready',
  'transname': ''},
 {'attributes': {'comparevalue': '${RETRY_MAX}',
                 'description': 'Conditional branch evaluation',
                 'draw': 'Y',
                 'fieldtype': 'NUMBER',
                 'nr': '0',
                 'parallel': 'N',
                 'successbooleancondition': 'false',
                 'successcondition': 'EQUAL',
                 'successnumbercondition': 'SMALLER',
                 'successwhenvarset': 'N',
                 'valuetype': 'VARIABLE',
                 'variablename': 'RETRY_COUNT',
                 'xloc': '1960',
                 'yloc': '280'},
  'entry_type': 'SIMPLE_EVAL',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Evaluate Retry Count',
  'transname': ''},
 {'attributes': {'description': 'Retry / throttle delay',
                 'draw': 'Y',
                 'maximumTimeout': '5',
                 'nr': '0',
                 'parallel': 'N',
                 'scaletime': '0',
                 'xloc': '2120',
                 'yloc': '280'},
  'entry_type': 'DELAY',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Retry Delay',
  'transname': ''},
 {'attributes': {'add_date': 'Y',
                 'add_time': 'Y',
                 'arg_from_previous': 'N',
                 'clear_files': 'N',
                 'clear_rows': 'N',
                 'cluster': 'N',
                 'description': 'PLACEHOLDER transformation (not generated yet): '
                                '${PROJECT_HOME}/transformations/lookup/FX_Rate_Lookup_Prep.ktr',
                 'draw': 'Y',
                 'exec_per_row': 'N',
                 'filename': '${PROJECT_HOME}/transformations/lookup/FX_Rate_Lookup_Prep.ktr',
                 'follow_abort_remote': 'Y',
                 'logext': 'log',
                 'logfile': '${LOG_MODULE_PATH}/FX_Rate_Lookup_Prep',
                 'loglevel': 'Basic',
                 'nr': '0',
                 'parallel': 'N',
                 'params_from_previous': 'N',
                 'set_logfile': 'Y',
                 'specification_method': 'filename',
                 'wait_until_finished': 'Y',
                 'xloc': '1960',
                 'yloc': '80'},
  'entry_type': 'TRANS',
  'filename': '${PROJECT_HOME}/transformations/lookup/FX_Rate_Lookup_Prep.ktr',
  'is_start': False,
  'jobname': '',
  'name': 'FX_Rate_Lookup_Prep',
  'transname': ''},
 {'attributes': {'add_date': 'Y',
                 'add_time': 'Y',
                 'arg_from_previous': 'N',
                 'clear_files': 'N',
                 'clear_rows': 'N',
                 'cluster': 'N',
                 'description': 'PLACEHOLDER transformation (not generated yet): '
                                '${PROJECT_HOME}/transformations/validation/Payments_Validation.ktr',
                 'draw': 'Y',
                 'exec_per_row': 'N',
                 'filename': '${PROJECT_HOME}/transformations/validation/Payments_Validation.ktr',
                 'follow_abort_remote': 'Y',
                 'logext': 'log',
                 'logfile': '${LOG_MODULE_PATH}/Payments_Validation',
                 'loglevel': 'Basic',
                 'nr': '0',
                 'parallel': 'N',
                 'params_from_previous': 'N',
                 'set_logfile': 'Y',
                 'specification_method': 'filename',
                 'wait_until_finished': 'Y',
                 'xloc': '2140',
                 'yloc': '80'},
  'entry_type': 'TRANS',
  'filename': '${PROJECT_HOME}/transformations/validation/Payments_Validation.ktr',
  'is_start': False,
  'jobname': '',
  'name': 'Payments_Validation',
  'transname': ''},
 {'attributes': {'add_date': 'Y',
                 'add_time': 'Y',
                 'arg_from_previous': 'N',
                 'clear_files': 'N',
                 'clear_rows': 'N',
                 'cluster': 'N',
                 'description': 'PLACEHOLDER transformation (not generated yet): '
                                '${PROJECT_HOME}/transformations/cleansing/Payments_Cleansing.ktr',
                 'draw': 'Y',
                 'exec_per_row': 'N',
                 'filename': '${PROJECT_HOME}/transformations/cleansing/Payments_Cleansing.ktr',
                 'follow_abort_remote': 'Y',
                 'logext': 'log',
                 'logfile': '${LOG_MODULE_PATH}/Payments_Cleansing',
                 'loglevel': 'Basic',
                 'nr': '0',
                 'parallel': 'N',
                 'params_from_previous': 'N',
                 'set_logfile': 'Y',
                 'specification_method': 'filename',
                 'wait_until_finished': 'Y',
                 'xloc': '2320',
                 'yloc': '80'},
  'entry_type': 'TRANS',
  'filename': '${PROJECT_HOME}/transformations/cleansing/Payments_Cleansing.ktr',
  'is_start': False,
  'jobname': '',
  'name': 'Payments_Cleansing',
  'transname': ''},
 {'attributes': {'add_date': 'Y',
                 'add_time': 'Y',
                 'arg_from_previous': 'N',
                 'clear_files': 'N',
                 'clear_rows': 'N',
                 'cluster': 'N',
                 'description': 'PLACEHOLDER transformation (not generated yet): '
                                '${PROJECT_HOME}/transformations/fact/Payments_Fact_Load.ktr',
                 'draw': 'Y',
                 'exec_per_row': 'N',
                 'filename': '${PROJECT_HOME}/transformations/fact/Payments_Fact_Load.ktr',
                 'follow_abort_remote': 'Y',
                 'logext': 'log',
                 'logfile': '${LOG_MODULE_PATH}/Payments_Fact_Load',
                 'loglevel': 'Basic',
                 'nr': '0',
                 'parallel': 'N',
                 'params_from_previous': 'N',
                 'set_logfile': 'Y',
                 'specification_method': 'filename',
                 'wait_until_finished': 'Y',
                 'xloc': '2500',
                 'yloc': '80'},
  'entry_type': 'TRANS',
  'filename': '${PROJECT_HOME}/transformations/fact/Payments_Fact_Load.ktr',
  'is_start': False,
  'jobname': '',
  'name': 'Payments_Fact_Load',
  'transname': ''},
 {'attributes': {'add_date': 'Y',
                 'add_time': 'Y',
                 'arg_from_previous': 'N',
                 'clear_files': 'N',
                 'clear_rows': 'N',
                 'cluster': 'N',
                 'description': 'PLACEHOLDER transformation (not generated yet): '
                                '${PROJECT_HOME}/transformations/validation/Shipments_Validation.ktr',
                 'draw': 'Y',
                 'exec_per_row': 'N',
                 'filename': '${PROJECT_HOME}/transformations/validation/Shipments_Validation.ktr',
                 'follow_abort_remote': 'Y',
                 'logext': 'log',
                 'logfile': '${LOG_MODULE_PATH}/Shipments_Validation',
                 'loglevel': 'Basic',
                 'nr': '0',
                 'parallel': 'N',
                 'params_from_previous': 'N',
                 'set_logfile': 'Y',
                 'specification_method': 'filename',
                 'wait_until_finished': 'Y',
                 'xloc': '2680',
                 'yloc': '80'},
  'entry_type': 'TRANS',
  'filename': '${PROJECT_HOME}/transformations/validation/Shipments_Validation.ktr',
  'is_start': False,
  'jobname': '',
  'name': 'Shipments_Validation',
  'transname': ''},
 {'attributes': {'add_date': 'Y',
                 'add_time': 'Y',
                 'arg_from_previous': 'N',
                 'clear_files': 'N',
                 'clear_rows': 'N',
                 'cluster': 'N',
                 'description': 'PLACEHOLDER transformation (not generated yet): '
                                '${PROJECT_HOME}/transformations/cleansing/Shipments_Cleansing.ktr',
                 'draw': 'Y',
                 'exec_per_row': 'N',
                 'filename': '${PROJECT_HOME}/transformations/cleansing/Shipments_Cleansing.ktr',
                 'follow_abort_remote': 'Y',
                 'logext': 'log',
                 'logfile': '${LOG_MODULE_PATH}/Shipments_Cleansing',
                 'loglevel': 'Basic',
                 'nr': '0',
                 'parallel': 'N',
                 'params_from_previous': 'N',
                 'set_logfile': 'Y',
                 'specification_method': 'filename',
                 'wait_until_finished': 'Y',
                 'xloc': '2860',
                 'yloc': '80'},
  'entry_type': 'TRANS',
  'filename': '${PROJECT_HOME}/transformations/cleansing/Shipments_Cleansing.ktr',
  'is_start': False,
  'jobname': '',
  'name': 'Shipments_Cleansing',
  'transname': ''},
 {'attributes': {'add_date': 'Y',
                 'add_time': 'Y',
                 'arg_from_previous': 'N',
                 'clear_files': 'N',
                 'clear_rows': 'N',
                 'cluster': 'N',
                 'description': 'PLACEHOLDER transformation (not generated yet): '
                                '${PROJECT_HOME}/transformations/fact/Shipments_Fact_Load.ktr',
                 'draw': 'Y',
                 'exec_per_row': 'N',
                 'filename': '${PROJECT_HOME}/transformations/fact/Shipments_Fact_Load.ktr',
                 'follow_abort_remote': 'Y',
                 'logext': 'log',
                 'logfile': '${LOG_MODULE_PATH}/Shipments_Fact_Load',
                 'loglevel': 'Basic',
                 'nr': '0',
                 'parallel': 'N',
                 'params_from_previous': 'N',
                 'set_logfile': 'Y',
                 'specification_method': 'filename',
                 'wait_until_finished': 'Y',
                 'xloc': '3040',
                 'yloc': '80'},
  'entry_type': 'TRANS',
  'filename': '${PROJECT_HOME}/transformations/fact/Shipments_Fact_Load.ktr',
  'is_start': False,
  'jobname': '',
  'name': 'Shipments_Fact_Load',
  'transname': ''},
 {'attributes': {'description': 'Audit / control SQL (placeholder connection)',
                 'draw': 'Y',
                 'nr': '0',
                 'parallel': 'N',
                 'sendOneStatement': 'N',
                 'sql': '-- Placeholder audit SQL for Load_Finance_Data\n'
                        '-- INSERT INTO audit_job_step (batch_id, job_name, status, log_ts)\n'
                        "-- VALUES ('${RUN_ID}', 'Load_Finance_Data', 'SUCCESS', "
                        'CURRENT_TIMESTAMP);',
                 'sqlfromfile': 'N',
                 'useVariableSubstitution': 'Y',
                 'xloc': '3220',
                 'yloc': '80'},
  'entry_type': 'SQL',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'SQL Audit Checkpoint',
  'transname': ''},
 {'attributes': {'description': 'Structured execution log',
                 'displayHeader': 'Y',
                 'draw': 'Y',
                 'limitRows': 'N',
                 'limitRowsNumber': '0',
                 'loglevel': 'BASIC',
                 'logmessage': 'AUDIT | EVENT=ROWS_PROCESSED | JOB=Load_Finance_Data | '
                               'RUN_ID=${RUN_ID} | NOTE=Row metrics will be supplied by '
                               'transformations when .ktr files are added',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '3380',
                 'yloc': '80'},
  'entry_type': 'WRITE_TO_LOG',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Log Rows Processed',
  'transname': ''},
 {'attributes': {'description': 'Structured execution log',
                 'displayHeader': 'Y',
                 'draw': 'Y',
                 'limitRows': 'N',
                 'limitRowsNumber': '0',
                 'loglevel': 'BASIC',
                 'logmessage': 'AUDIT | EVENT=JOB_COMPLETED | JOB=Load_Finance_Data | '
                               'RUN_ID=${RUN_ID} | STATUS=SUCCESS | EXECUTION_TIME=SEE_ENGINE_LOG',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '3540',
                 'yloc': '80'},
  'entry_type': 'WRITE_TO_LOG',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Log Job Completed',
  'transname': ''},
 {'attributes': {'description': 'Terminal success',
                 'draw': 'Y',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '3700',
                 'yloc': '80'},
  'entry_type': 'SUCCESS',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Success',
  'transname': ''},
 {'attributes': {'description': 'Structured execution log',
                 'displayHeader': 'Y',
                 'draw': 'Y',
                 'limitRows': 'N',
                 'limitRowsNumber': '0',
                 'loglevel': 'ERROR',
                 'logmessage': 'FAILURE | Job=${Internal.Job.Name} | RUN_ID=${RUN_ID} | '
                               'CURRENT_DATE=${CURRENT_DATE} | Check ${REJECT_PATH} and '
                               '${LOG_PATH}',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '480',
                 'yloc': '420'},
  'entry_type': 'WRITE_TO_LOG',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Log Failure',
  'transname': ''},
 {'attributes': {'comment': 'Job ${Internal.Job.Name} failed. RUN_ID=${RUN_ID}. Inspect '
                            '${LOG_PATH}/execution and ${REJECT_PATH}/exception_reports.',
                 'description': 'Dummy notification (mail disabled by default)',
                 'destination': '${MAIL_TO}',
                 'draw': 'Y',
                 'encoding': 'UTF-8',
                 'importance': 'normal',
                 'include_files': 'N',
                 'include_subfolders': 'N',
                 'nr': '0',
                 'only_comment': 'N',
                 'parallel': 'N',
                 'port': '25',
                 'priority': 'normal',
                 'replyto': 'etl-noreply@example.com',
                 'secureconnectiontype': 'SSL',
                 'sender_address': 'etl-noreply@example.com',
                 'sender_name': 'Retail ETL',
                 'sensitivity': 'normal',
                 'server': 'localhost',
                 'subject': '[FAIL] Retail ETL ${Internal.Job.Name} RUN_ID=${RUN_ID}',
                 'use_HTML': 'N',
                 'use_Priority': 'N',
                 'use_auth': 'N',
                 'use_secure_auth': 'N',
                 'xloc': '700',
                 'yloc': '420',
                 'zip_files': 'N'},
  'entry_type': 'MAIL',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Failure Email Dummy',
  'transname': ''},
 {'attributes': {'description': 'Terminal abort on unrecoverable failure',
                 'draw': 'Y',
                 'message': 'Aborting ${Internal.Job.Name} for RUN_ID=${RUN_ID}. See error logs.',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '920',
                 'yloc': '420'},
  'entry_type': 'ABORT',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Abort on Failure',
  'transname': ''}]

HOP_DEFS = [{'enabled': True,
  'evaluation': True,
  'from_name': 'Start',
  'to_name': 'Log Job Started',
  'unconditional': True},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Log Job Started',
  'to_name': 'Ensure Path Variables',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Ensure Path Variables',
  'to_name': 'Create Module Reject Folder',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Create Module Reject Folder',
  'to_name': 'Create Module Log Folder',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Create Module Log Folder',
  'to_name': 'File Exists payments.csv',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'File Exists payments.csv',
  'to_name': 'File Exists shipments.csv',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'File Exists shipments.csv',
  'to_name': 'File Exists exchange_rates.csv',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'File Exists exchange_rates.csv',
  'to_name': 'Unzip Reference Package Optional',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Unzip Reference Package Optional',
  'to_name': 'Continue After Optional Unzip',
  'unconditional': True},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Continue After Optional Unzip',
  'to_name': 'Wait For Primary Source',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Wait For Primary Source',
  'to_name': 'Log Sources Ready',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Log Sources Ready',
  'to_name': 'FX_Rate_Lookup_Prep',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'FX_Rate_Lookup_Prep',
  'to_name': 'Payments_Validation',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Payments_Validation',
  'to_name': 'Payments_Cleansing',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Payments_Cleansing',
  'to_name': 'Payments_Fact_Load',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Payments_Fact_Load',
  'to_name': 'Shipments_Validation',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Shipments_Validation',
  'to_name': 'Shipments_Cleansing',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Shipments_Cleansing',
  'to_name': 'Shipments_Fact_Load',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Shipments_Fact_Load',
  'to_name': 'SQL Audit Checkpoint',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'SQL Audit Checkpoint',
  'to_name': 'Log Rows Processed',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Log Rows Processed',
  'to_name': 'Log Job Completed',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Log Job Completed',
  'to_name': 'Success',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'FX_Rate_Lookup_Prep',
  'to_name': 'Evaluate Retry Count',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Evaluate Retry Count',
  'to_name': 'Retry Delay',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Retry Delay',
  'to_name': 'FX_Rate_Lookup_Prep',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Create Module Reject Folder',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'File Exists payments.csv',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'File Exists shipments.csv',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'File Exists exchange_rates.csv',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'FX_Rate_Lookup_Prep',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Payments_Validation',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Payments_Cleansing',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Payments_Fact_Load',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Shipments_Validation',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Shipments_Cleansing',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Shipments_Fact_Load',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Log Failure',
  'to_name': 'Failure Email Dummy',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Failure Email Dummy',
  'to_name': 'Abort on Failure',
  'unconditional': True},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Evaluate Retry Count',
  'to_name': 'Log Failure',
  'unconditional': False}]

# Parent job entry name -> retail module stem
TRANS_MODULES = {'FX_Rate_Lookup_Prep': ('fx_rate_lookup_prep', 'FX_Rate_Lookup_Prep'),
 'Payments_Cleansing': ('payments_cleansing', 'Payments_Cleansing'),
 'Payments_Fact_Load': ('payments_fact_load', 'Payments_Fact_Load'),
 'Payments_Validation': ('payments_validation', 'Payments_Validation'),
 'Shipments_Cleansing': ('shipments_cleansing', 'Shipments_Cleansing'),
 'Shipments_Fact_Load': ('shipments_fact_load', 'Shipments_Fact_Load'),
 'Shipments_Validation': ('shipments_validation', 'Shipments_Validation')}


def _entries() -> list[JobEntry]:
    return [
        JobEntry(
            name=d["name"],
            entry_type=d["entry_type"],
            filename=d.get("filename", ""),
            transname=d.get("transname", ""),
            jobname=d.get("jobname", ""),
            is_start=bool(d.get("is_start")),
            attributes=dict(d.get("attributes") or {}),
        )
        for d in ENTRY_DEFS
    ]


def _hops() -> list[JobHop]:
    return [
        JobHop(
            from_name=h["from_name"],
            to_name=h["to_name"],
            enabled=bool(h.get("enabled", True)),
            unconditional=h.get("unconditional"),
            evaluation=h.get("evaluation"),
        )
        for h in HOP_DEFS
    ]


def _handle_special(runtime: JobRuntime, entry: JobEntry) -> EntryResult:
    return EntryResult(name=entry.name, success=True, result=True)


def _handle_success(runtime: JobRuntime, entry: JobEntry) -> EntryResult:
    return EntryResult(name=entry.name, success=True, result=True)


def _handle_abort(runtime: JobRuntime, entry: JobEntry) -> EntryResult:
    msg = entry.attributes.get("message") or f"Abort at {entry.name}"
    return EntryResult(
        name=entry.name,
        success=False,
        result=msg,
        error=JobExecutionError(msg),
    )


def _handle_trans(
    runtime: JobRuntime,
    entry: JobEntry,
    *,
    spark: Any,
    config: Mapping[str, Any],
) -> EntryResult:
    mapping = TRANS_MODULES.get(entry.name)
    if not mapping:
        return EntryResult(
            name=entry.name,
            success=False,
            error=JobExecutionError(f"No TRANS module mapping for {entry.name}"),
        )
    py_stem, ktr_stem = mapping
    resolved = substitute_variables(entry.filename, runtime.variables)
    try:
        module = importlib.import_module(
            f"pentaho_migration.transformations.retail.{py_stem}"
        )
        child_cfg = dict(config)
        child_cfg.update({k: str(v) for k, v in runtime.variables.items()})
        df = module.run(spark, child_cfg)
        logger.info(
            "TRANS OK | entry=%s | module=%s | resolved=%s",
            entry.name,
            py_stem,
            resolved,
        )
        return EntryResult(name=entry.name, success=True, result=df)
    except Exception as exc:  # noqa: BLE001
        logger.exception("TRANS FAIL | entry=%s | module=%s", entry.name, py_stem)
        return EntryResult(name=entry.name, success=False, error=exc)


def run(spark: Any = None, config: Mapping[str, Any] | None = None) -> Any:
    """Execute expanded child job ``Load_Finance_Data``."""
    config = dict(config or {})
    if spark is not None:
        apply_spark_runtime_hints(spark, config)
    log_event(_LOG, "job_start", job=JOB_NAME)
    variables = {
        "Internal.Job.Name": JOB_NAME,
        "Internal.Job.Filename.Name": SOURCE_KJB,
        **{k: str(v) for k, v in config.items()},
    }

    def handle_trans(runtime: JobRuntime, entry: JobEntry) -> EntryResult:
        return _handle_trans(runtime, entry, spark=spark, config=config)

    runtime = JobRuntime(
        name=JOB_NAME,
        entries=_entries(),
        hops=_hops(),
        parameters={k: str(v) for k, v in config.items() if isinstance(v, (str, int, float))},
        variables=variables,
        handlers={
            "SPECIAL": _handle_special,
            "SUCCESS": _handle_success,
            "ABORT": _handle_abort,
            "TRANS": handle_trans,
        },
        allow_reentry=True,
    )
    final = runtime.run()
    log_event(_LOG, "job_end", success=final.success, last=final.name,
              steps=len(runtime.executed))
    if not final.success:
        raise JobExecutionError(
            f"Child job {JOB_NAME} failed at {final.name}"
        ) from final.error
    return {
        "job": JOB_NAME,
        "expanded": True,
        "executed": list(runtime.executed),
        "result": final.result,
    }
