# Auto-generated from Master_ETL.kjb — do not edit by hand.
JOB_PARAMETERS = {'DATASET_PATH': '',
 'MAIL_ENABLED': 'N',
 'MAIL_TO': 'etl-ops@example.com',
 'PROJECT_HOME': '',
 'RUN_ID': ''}

ENTRY_DEFS = [{'attributes': {'DayOfMonth': '1',
                 'description': 'Job entry point',
                 'draw': 'Y',
                 'dummy': 'N',
                 'hour': '12',
                 'intervalMinutes': '60',
                 'intervalSeconds': '0',
                 'minutes': '0',
                 'nr': '0',
                 'parallel': 'N',
                 'repeat': 'N',
                 'schedulerType': '0',
                 'weekDay': '1',
                 'xloc': '48',
                 'yloc': '80'},
  'entry_type': 'SPECIAL',
  'filename': '',
  'is_start': True,
  'jobname': '',
  'name': 'Start',
  'transname': ''},
 {'attributes': {'description': 'Structured execution log',
                 'displayHeader': 'Y',
                 'draw': 'Y',
                 'limitRows': 'N',
                 'limitRowsNumber': '0',
                 'loglevel': 'BASIC',
                 'logmessage': 'AUDIT | EVENT=JOB_STARTED | JOB=Master_ETL | RUN_ID=${RUN_ID} | '
                               'DATE=${CURRENT_DATE}',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '180',
                 'yloc': '80'},
  'entry_type': 'WRITE_TO_LOG',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Log Job Started',
  'transname': ''},
 {'attributes': {'description': 'Initialize / refresh variables',
                 'draw': 'Y',
                 'fields': [{'variable_name': 'PROJECT_HOME',
                             'variable_string': '${Internal.Job.Filename.Directory}/../..',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'DATASET_PATH',
                             'variable_string': '${PROJECT_HOME}/../Retail_Dataset',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'LOG_PATH',
                             'variable_string': '${PROJECT_HOME}/logs',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'REJECT_PATH',
                             'variable_string': '${PROJECT_HOME}/rejects',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'OUTPUT_PATH',
                             'variable_string': '${PROJECT_HOME}/output',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'ARCHIVE_PATH',
                             'variable_string': '${PROJECT_HOME}/archive',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'CURRENT_DATE',
                             'variable_string': '${%yyyy-MM-dd}',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'RUN_ID',
                             'variable_string': '${%yyyyMMdd_HHmmss}',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'MAIL_TO',
                             'variable_string': 'etl-ops@example.com',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'MAIL_ENABLED',
                             'variable_string': 'N',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'RETRY_COUNT',
                             'variable_string': '0',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'RETRY_MAX',
                             'variable_string': '3',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'VAR_PATH_PROJECT_ROOT',
                             'variable_string': '${PROJECT_HOME}',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'VAR_PATH_DATA_ROOT',
                             'variable_string': '${DATASET_PATH}',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'VAR_PATH_LOGS',
                             'variable_string': '${LOG_PATH}',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'VAR_PATH_REJECTS',
                             'variable_string': '${REJECT_PATH}',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'VAR_PATH_OUTPUT',
                             'variable_string': '${OUTPUT_PATH}',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'VAR_PATH_AUDIT',
                             'variable_string': '${PROJECT_HOME}/audit',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'VAR_ETL_BATCH_ID',
                             'variable_string': '${RUN_ID}',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'VAR_ETL_BATCH_DATE',
                             'variable_string': '${CURRENT_DATE}',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'VAR_ETL_RUN_MODE',
                             'variable_string': 'FULL',
                             'variable_type': 'ROOT_JOB'},
                            {'variable_name': 'VAR_ENV_NAME',
                             'variable_string': 'DEV',
                             'variable_type': 'ROOT_JOB'}],
                 'file_variable_type': 'JVM',
                 'nr': '0',
                 'parallel': 'N',
                 'replace': 'Y',
                 'xloc': '340',
                 'yloc': '80'},
  'entry_type': 'SET_VARIABLES',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Initialize Variables',
  'transname': ''},
 {'attributes': {'add_date': 'N',
                 'add_time': 'N',
                 'arg_from_previous': 'N',
                 'description': 'Operating-system helper',
                 'draw': 'Y',
                 'exec_per_row': 'N',
                 'insertScript': 'Y',
                 'loglevel': 'Basic',
                 'nr': '0',
                 'parallel': 'N',
                 'script': 'echo Master_ETL RUN_ID=%RUN_ID% PROJECT_HOME=%PROJECT_HOME% '
                           'CURRENT_DATE=%CURRENT_DATE%',
                 'set_append_logfile': 'N',
                 'set_logfile': 'N',
                 'work_directory': '${PROJECT_HOME}',
                 'xloc': '500',
                 'yloc': '80'},
  'entry_type': 'SHELL',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Echo Batch Context',
  'transname': ''},
 {'attributes': {'description': 'Ensure folder exists: ${LOG_PATH}/execution',
                 'draw': 'Y',
                 'fail_of_folder_exists': 'N',
                 'foldername': '${LOG_PATH}/execution',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '660',
                 'yloc': '40'},
  'entry_type': 'CREATE_FOLDER',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Create Log Folder',
  'transname': ''},
 {'attributes': {'description': 'Ensure folder exists: ${REJECT_PATH}/rejected_rows',
                 'draw': 'Y',
                 'fail_of_folder_exists': 'N',
                 'foldername': '${REJECT_PATH}/rejected_rows',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '660',
                 'yloc': '100'},
  'entry_type': 'CREATE_FOLDER',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Create Reject Folder',
  'transname': ''},
 {'attributes': {'description': 'Ensure folder exists: ${OUTPUT_PATH}/staging/temp',
                 'draw': 'Y',
                 'fail_of_folder_exists': 'N',
                 'foldername': '${OUTPUT_PATH}/staging/temp',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '660',
                 'yloc': '160'},
  'entry_type': 'CREATE_FOLDER',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Create Output Folder',
  'transname': ''},
 {'attributes': {'description': 'Ensure folder exists: ${ARCHIVE_PATH}/${CURRENT_DATE}',
                 'draw': 'Y',
                 'fail_of_folder_exists': 'N',
                 'foldername': '${ARCHIVE_PATH}/${CURRENT_DATE}',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '820',
                 'yloc': '40'},
  'entry_type': 'CREATE_FOLDER',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Create Archive Folder',
  'transname': ''},
 {'attributes': {'description': 'Ensure folder exists: ${PROJECT_HOME}/audit/load_audit',
                 'draw': 'Y',
                 'fail_of_folder_exists': 'N',
                 'foldername': '${PROJECT_HOME}/audit/load_audit',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '820',
                 'yloc': '100'},
  'entry_type': 'CREATE_FOLDER',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Create Audit Folder',
  'transname': ''},
 {'attributes': {'DayOfMonth': '1',
                 'description': 'All runtime folders verified',
                 'draw': 'Y',
                 'dummy': 'Y',
                 'hour': '12',
                 'intervalMinutes': '60',
                 'intervalSeconds': '0',
                 'minutes': '0',
                 'nr': '0',
                 'parallel': 'N',
                 'repeat': 'N',
                 'schedulerType': '0',
                 'weekDay': '1',
                 'xloc': '980',
                 'yloc': '80'},
  'entry_type': 'SPECIAL',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Folders Ready',
  'transname': ''},
 {'attributes': {'addFilenameResult': 'N',
                 'checkCycleTime': '5',
                 'description': 'SLA wait for source drop',
                 'draw': 'Y',
                 'fileSizeCheck': 'N',
                 'filename': '${DATASET_PATH}/customers.csv',
                 'maximumTimeout': '30',
                 'nr': '0',
                 'parallel': 'N',
                 'successOnTimeout': 'Y',
                 'xloc': '1140',
                 'yloc': '80'},
  'entry_type': 'WAIT_FOR_FILE',
  'filename': '${DATASET_PATH}/customers.csv',
  'is_start': False,
  'jobname': '',
  'name': 'Wait For Source Flag Optional',
  'transname': ''},
 {'attributes': {'SpecifyFormat': 'N',
                 'adddate': 'Y',
                 'addfileparent': 'N',
                 'addtime': 'Y',
                 'afterzip': '0',
                 'compressionrate': '1',
                 'createMoveToDirectory': 'N',
                 'createparentfolder': 'Y',
                 'description': 'Zip prior outputs for archive',
                 'draw': 'Y',
                 'iffileexists': '0',
                 'isfromprevious': 'N',
                 'nr': '0',
                 'parallel': 'N',
                 'sourcedirectory': '${OUTPUT_PATH}/exports',
                 'storedsourcepath': '0',
                 'wildCard': '.*',
                 'xloc': '1300',
                 'yloc': '80',
                 'zipfilename': '${ARCHIVE_PATH}/${CURRENT_DATE}/exports_${RUN_ID}.zip'},
  'entry_type': 'ZIP_FILE',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Archive Previous Outputs',
  'transname': ''},
 {'attributes': {'add_result_filesname': 'N',
                 'arg_from_previous': 'N',
                 'createDestinationFolder': 'Y',
                 'description': 'Archive / stage file copy',
                 'destination_filefolder': '${ARCHIVE_PATH}/${CURRENT_DATE}/logs',
                 'destination_is_afile': 'N',
                 'draw': 'Y',
                 'include_subfolders': 'N',
                 'nr': '0',
                 'overwrite_files': 'Y',
                 'parallel': 'N',
                 'remove_source_files': 'N',
                 'source_filefolder': '${LOG_PATH}/execution',
                 'source_wildcard': '.*\\.log$',
                 'xloc': '1460',
                 'yloc': '80'},
  'entry_type': 'COPY_FILES',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Copy Prior Logs To Archive',
  'transname': ''},
 {'attributes': {'description': 'Structured execution log',
                 'displayHeader': 'Y',
                 'draw': 'Y',
                 'limitRows': 'N',
                 'limitRowsNumber': '0',
                 'loglevel': 'BASIC',
                 'logmessage': 'AUDIT | EVENT=INIT_COMPLETE | RUN_ID=${RUN_ID} | '
                               'DATASET_PATH=${DATASET_PATH}',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '1620',
                 'yloc': '80'},
  'entry_type': 'WRITE_TO_LOG',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Log Init Complete',
  'transname': ''},
 {'attributes': {'add_date': 'Y',
                 'add_time': 'Y',
                 'arg_from_previous': 'N',
                 'description': 'Execute child job: '
                                '${Internal.Entry.Current.Directory}/../master_data/Load_Master_Data.kjb',
                 'draw': 'Y',
                 'exec_per_row': 'N',
                 'expand_selected_params': 'Y',
                 'filename': '${Internal.Entry.Current.Directory}/../master_data/Load_Master_Data.kjb',
                 'follow_abort_remote': 'Y',
                 'logext': 'log',
                 'logfile': '${LOG_PATH}/execution/Load_Master_Data',
                 'loglevel': 'Basic',
                 'nr': '0',
                 'parallel': 'N',
                 'params_from_previous': 'N',
                 'pass_all_parameters': 'Y',
                 'set_logfile': 'Y',
                 'specification_method': 'filename',
                 'wait_until_finished': 'Y',
                 'xloc': '1800',
                 'yloc': '80'},
  'entry_type': 'JOB',
  'filename': '${Internal.Entry.Current.Directory}/../master_data/Load_Master_Data.kjb',
  'is_start': False,
  'jobname': '',
  'name': 'Load Master Data',
  'transname': ''},
 {'attributes': {'add_date': 'Y',
                 'add_time': 'Y',
                 'arg_from_previous': 'N',
                 'description': 'Execute child job: '
                                '${Internal.Entry.Current.Directory}/../customer/Load_Customer_Data.kjb',
                 'draw': 'Y',
                 'exec_per_row': 'N',
                 'expand_selected_params': 'Y',
                 'filename': '${Internal.Entry.Current.Directory}/../customer/Load_Customer_Data.kjb',
                 'follow_abort_remote': 'Y',
                 'logext': 'log',
                 'logfile': '${LOG_PATH}/execution/Load_Customers',
                 'loglevel': 'Basic',
                 'nr': '0',
                 'parallel': 'N',
                 'params_from_previous': 'N',
                 'pass_all_parameters': 'Y',
                 'set_logfile': 'Y',
                 'specification_method': 'filename',
                 'wait_until_finished': 'Y',
                 'xloc': '1960',
                 'yloc': '80'},
  'entry_type': 'JOB',
  'filename': '${Internal.Entry.Current.Directory}/../customer/Load_Customer_Data.kjb',
  'is_start': False,
  'jobname': '',
  'name': 'Load Customers',
  'transname': ''},
 {'attributes': {'add_date': 'Y',
                 'add_time': 'Y',
                 'arg_from_previous': 'N',
                 'description': 'Execute child job: '
                                '${Internal.Entry.Current.Directory}/../product/Load_Product_Data.kjb',
                 'draw': 'Y',
                 'exec_per_row': 'N',
                 'expand_selected_params': 'Y',
                 'filename': '${Internal.Entry.Current.Directory}/../product/Load_Product_Data.kjb',
                 'follow_abort_remote': 'Y',
                 'logext': 'log',
                 'logfile': '${LOG_PATH}/execution/Load_Products',
                 'loglevel': 'Basic',
                 'nr': '0',
                 'parallel': 'N',
                 'params_from_previous': 'N',
                 'pass_all_parameters': 'Y',
                 'set_logfile': 'Y',
                 'specification_method': 'filename',
                 'wait_until_finished': 'Y',
                 'xloc': '2120',
                 'yloc': '80'},
  'entry_type': 'JOB',
  'filename': '${Internal.Entry.Current.Directory}/../product/Load_Product_Data.kjb',
  'is_start': False,
  'jobname': '',
  'name': 'Load Products',
  'transname': ''},
 {'attributes': {'add_date': 'Y',
                 'add_time': 'Y',
                 'arg_from_previous': 'N',
                 'description': 'Execute child job: '
                                '${Internal.Entry.Current.Directory}/../inventory/Load_Inventory_Data.kjb',
                 'draw': 'Y',
                 'exec_per_row': 'N',
                 'expand_selected_params': 'Y',
                 'filename': '${Internal.Entry.Current.Directory}/../inventory/Load_Inventory_Data.kjb',
                 'follow_abort_remote': 'Y',
                 'logext': 'log',
                 'logfile': '${LOG_PATH}/execution/Load_Inventory',
                 'loglevel': 'Basic',
                 'nr': '0',
                 'parallel': 'N',
                 'params_from_previous': 'N',
                 'pass_all_parameters': 'Y',
                 'set_logfile': 'Y',
                 'specification_method': 'filename',
                 'wait_until_finished': 'Y',
                 'xloc': '2280',
                 'yloc': '80'},
  'entry_type': 'JOB',
  'filename': '${Internal.Entry.Current.Directory}/../inventory/Load_Inventory_Data.kjb',
  'is_start': False,
  'jobname': '',
  'name': 'Load Inventory',
  'transname': ''},
 {'attributes': {'add_date': 'Y',
                 'add_time': 'Y',
                 'arg_from_previous': 'N',
                 'description': 'Execute child job: '
                                '${Internal.Entry.Current.Directory}/../sales/Load_Sales_Data.kjb',
                 'draw': 'Y',
                 'exec_per_row': 'N',
                 'expand_selected_params': 'Y',
                 'filename': '${Internal.Entry.Current.Directory}/../sales/Load_Sales_Data.kjb',
                 'follow_abort_remote': 'Y',
                 'logext': 'log',
                 'logfile': '${LOG_PATH}/execution/Load_Sales',
                 'loglevel': 'Basic',
                 'nr': '0',
                 'parallel': 'N',
                 'params_from_previous': 'N',
                 'pass_all_parameters': 'Y',
                 'set_logfile': 'Y',
                 'specification_method': 'filename',
                 'wait_until_finished': 'Y',
                 'xloc': '2440',
                 'yloc': '80'},
  'entry_type': 'JOB',
  'filename': '${Internal.Entry.Current.Directory}/../sales/Load_Sales_Data.kjb',
  'is_start': False,
  'jobname': '',
  'name': 'Load Sales',
  'transname': ''},
 {'attributes': {'add_date': 'Y',
                 'add_time': 'Y',
                 'arg_from_previous': 'N',
                 'description': 'Execute child job: '
                                '${Internal.Entry.Current.Directory}/../finance/Load_Finance_Data.kjb',
                 'draw': 'Y',
                 'exec_per_row': 'N',
                 'expand_selected_params': 'Y',
                 'filename': '${Internal.Entry.Current.Directory}/../finance/Load_Finance_Data.kjb',
                 'follow_abort_remote': 'Y',
                 'logext': 'log',
                 'logfile': '${LOG_PATH}/execution/Load_Finance',
                 'loglevel': 'Basic',
                 'nr': '0',
                 'parallel': 'N',
                 'params_from_previous': 'N',
                 'pass_all_parameters': 'Y',
                 'set_logfile': 'Y',
                 'specification_method': 'filename',
                 'wait_until_finished': 'Y',
                 'xloc': '2600',
                 'yloc': '80'},
  'entry_type': 'JOB',
  'filename': '${Internal.Entry.Current.Directory}/../finance/Load_Finance_Data.kjb',
  'is_start': False,
  'jobname': '',
  'name': 'Load Finance',
  'transname': ''},
 {'attributes': {'add_date': 'Y',
                 'add_time': 'Y',
                 'arg_from_previous': 'N',
                 'description': 'Execute child job: '
                                '${Internal.Entry.Current.Directory}/../reporting/Load_Reporting_Data.kjb',
                 'draw': 'Y',
                 'exec_per_row': 'N',
                 'expand_selected_params': 'Y',
                 'filename': '${Internal.Entry.Current.Directory}/../reporting/Load_Reporting_Data.kjb',
                 'follow_abort_remote': 'Y',
                 'logext': 'log',
                 'logfile': '${LOG_PATH}/execution/Load_Reporting',
                 'loglevel': 'Basic',
                 'nr': '0',
                 'parallel': 'N',
                 'params_from_previous': 'N',
                 'pass_all_parameters': 'Y',
                 'set_logfile': 'Y',
                 'specification_method': 'filename',
                 'wait_until_finished': 'Y',
                 'xloc': '2760',
                 'yloc': '80'},
  'entry_type': 'JOB',
  'filename': '${Internal.Entry.Current.Directory}/../reporting/Load_Reporting_Data.kjb',
  'is_start': False,
  'jobname': '',
  'name': 'Load Reporting',
  'transname': ''},
 {'attributes': {'add_date': 'Y',
                 'add_time': 'Y',
                 'arg_from_previous': 'N',
                 'description': 'Execute child job: '
                                '${Internal.Entry.Current.Directory}/../utilities/Cleanup.kjb',
                 'draw': 'Y',
                 'exec_per_row': 'N',
                 'expand_selected_params': 'Y',
                 'filename': '${Internal.Entry.Current.Directory}/../utilities/Cleanup.kjb',
                 'follow_abort_remote': 'Y',
                 'logext': 'log',
                 'logfile': '${LOG_PATH}/execution/Cleanup_Temporary_Files',
                 'loglevel': 'Basic',
                 'nr': '0',
                 'parallel': 'N',
                 'params_from_previous': 'N',
                 'pass_all_parameters': 'Y',
                 'set_logfile': 'Y',
                 'specification_method': 'filename',
                 'wait_until_finished': 'Y',
                 'xloc': '2920',
                 'yloc': '80'},
  'entry_type': 'JOB',
  'filename': '${Internal.Entry.Current.Directory}/../utilities/Cleanup.kjb',
  'is_start': False,
  'jobname': '',
  'name': 'Cleanup Temporary Files',
  'transname': ''},
 {'attributes': {'add_date': 'Y',
                 'add_time': 'Y',
                 'arg_from_previous': 'N',
                 'description': 'Execute child job: '
                                '${Internal.Entry.Current.Directory}/../utilities/Audit.kjb',
                 'draw': 'Y',
                 'exec_per_row': 'N',
                 'expand_selected_params': 'Y',
                 'filename': '${Internal.Entry.Current.Directory}/../utilities/Audit.kjb',
                 'follow_abort_remote': 'Y',
                 'logext': 'log',
                 'logfile': '${LOG_PATH}/execution/Generate_Audit_Report',
                 'loglevel': 'Basic',
                 'nr': '0',
                 'parallel': 'N',
                 'params_from_previous': 'N',
                 'pass_all_parameters': 'Y',
                 'set_logfile': 'Y',
                 'specification_method': 'filename',
                 'wait_until_finished': 'Y',
                 'xloc': '3080',
                 'yloc': '80'},
  'entry_type': 'JOB',
  'filename': '${Internal.Entry.Current.Directory}/../utilities/Audit.kjb',
  'is_start': False,
  'jobname': '',
  'name': 'Generate Audit Report',
  'transname': ''},
 {'attributes': {'add_date': 'Y',
                 'add_time': 'Y',
                 'arg_from_previous': 'N',
                 'description': 'Execute child job: '
                                '${Internal.Entry.Current.Directory}/../utilities/Notification.kjb',
                 'draw': 'Y',
                 'exec_per_row': 'N',
                 'expand_selected_params': 'Y',
                 'filename': '${Internal.Entry.Current.Directory}/../utilities/Notification.kjb',
                 'follow_abort_remote': 'Y',
                 'logext': 'log',
                 'logfile': '${LOG_PATH}/execution/Success_Email_Dummy',
                 'loglevel': 'Basic',
                 'nr': '0',
                 'parallel': 'N',
                 'params_from_previous': 'N',
                 'pass_all_parameters': 'Y',
                 'set_logfile': 'Y',
                 'specification_method': 'filename',
                 'wait_until_finished': 'Y',
                 'xloc': '3240',
                 'yloc': '80'},
  'entry_type': 'JOB',
  'filename': '${Internal.Entry.Current.Directory}/../utilities/Notification.kjb',
  'is_start': False,
  'jobname': '',
  'name': 'Success Email Dummy',
  'transname': ''},
 {'attributes': {'description': 'Structured execution log',
                 'displayHeader': 'Y',
                 'draw': 'Y',
                 'limitRows': 'N',
                 'limitRowsNumber': '0',
                 'loglevel': 'BASIC',
                 'logmessage': 'AUDIT | EVENT=JOB_COMPLETED | JOB=Master_ETL | RUN_ID=${RUN_ID} | '
                               'STATUS=SUCCESS | OUTPUT=${OUTPUT_PATH}',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '3400',
                 'yloc': '80'},
  'entry_type': 'WRITE_TO_LOG',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Log Job Completed',
  'transname': ''},
 {'attributes': {'description': 'Terminal success',
                 'draw': 'Y',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '3560',
                 'yloc': '80'},
  'entry_type': 'SUCCESS',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Success',
  'transname': ''},
 {'attributes': {'comparevalue': '${RETRY_MAX}',
                 'description': 'Conditional branch evaluation',
                 'draw': 'Y',
                 'fieldtype': 'NUMBER',
                 'nr': '0',
                 'parallel': 'N',
                 'successbooleancondition': 'false',
                 'successcondition': 'EQUAL',
                 'successnumbercondition': 'SMALLER',
                 'successwhenvarset': 'N',
                 'valuetype': 'VARIABLE',
                 'variablename': 'RETRY_COUNT',
                 'xloc': '2280',
                 'yloc': '300'},
  'entry_type': 'SIMPLE_EVAL',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Evaluate Retry Allowed',
  'transname': ''},
 {'attributes': {'description': 'Retry / throttle delay',
                 'draw': 'Y',
                 'maximumTimeout': '10',
                 'nr': '0',
                 'parallel': 'N',
                 'scaletime': '0',
                 'xloc': '2440',
                 'yloc': '300'},
  'entry_type': 'DELAY',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Retry Delay',
  'transname': ''},
 {'attributes': {'description': 'Initialize / refresh variables',
                 'draw': 'Y',
                 'fields': [{'variable_name': 'RETRY_COUNT',
                             'variable_string': '${RETRY_COUNT}+1',
                             'variable_type': 'ROOT_JOB'}],
                 'file_variable_type': 'JVM',
                 'nr': '0',
                 'parallel': 'N',
                 'replace': 'Y',
                 'xloc': '2600',
                 'yloc': '300'},
  'entry_type': 'SET_VARIABLES',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Increment Retry Count',
  'transname': ''},
 {'attributes': {'description': 'Structured execution log',
                 'displayHeader': 'Y',
                 'draw': 'Y',
                 'limitRows': 'N',
                 'limitRowsNumber': '0',
                 'loglevel': 'ERROR',
                 'logmessage': 'FAILURE | Job=${Internal.Job.Name} | RUN_ID=${RUN_ID} | '
                               'CURRENT_DATE=${CURRENT_DATE} | Check ${REJECT_PATH} and '
                               '${LOG_PATH}',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '480',
                 'yloc': '420'},
  'entry_type': 'WRITE_TO_LOG',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Log Failure',
  'transname': ''},
 {'attributes': {'comment': 'Job ${Internal.Job.Name} failed. RUN_ID=${RUN_ID}. Inspect '
                            '${LOG_PATH}/execution and ${REJECT_PATH}/exception_reports.',
                 'description': 'Dummy notification (mail disabled by default)',
                 'destination': '${MAIL_TO}',
                 'draw': 'Y',
                 'encoding': 'UTF-8',
                 'importance': 'normal',
                 'include_files': 'N',
                 'include_subfolders': 'N',
                 'nr': '0',
                 'only_comment': 'N',
                 'parallel': 'N',
                 'port': '25',
                 'priority': 'normal',
                 'replyto': 'etl-noreply@example.com',
                 'secureconnectiontype': 'SSL',
                 'sender_address': 'etl-noreply@example.com',
                 'sender_name': 'Retail ETL',
                 'sensitivity': 'normal',
                 'server': 'localhost',
                 'subject': '[FAIL] Retail ETL ${Internal.Job.Name} RUN_ID=${RUN_ID}',
                 'use_HTML': 'N',
                 'use_Priority': 'N',
                 'use_auth': 'N',
                 'use_secure_auth': 'N',
                 'xloc': '700',
                 'yloc': '420',
                 'zip_files': 'N'},
  'entry_type': 'MAIL',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Failure Email Dummy',
  'transname': ''},
 {'attributes': {'description': 'Terminal abort on unrecoverable failure',
                 'draw': 'Y',
                 'message': 'Aborting ${Internal.Job.Name} for RUN_ID=${RUN_ID}. See error logs.',
                 'nr': '0',
                 'parallel': 'N',
                 'xloc': '920',
                 'yloc': '420'},
  'entry_type': 'ABORT',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Abort on Failure',
  'transname': ''},
 {'attributes': {'DayOfMonth': '1',
                 'description': 'Optional retry entry point',
                 'draw': 'Y',
                 'dummy': 'Y',
                 'hour': '12',
                 'intervalMinutes': '60',
                 'intervalSeconds': '0',
                 'minutes': '0',
                 'nr': '0',
                 'parallel': 'N',
                 'repeat': 'N',
                 'schedulerType': '0',
                 'weekDay': '1',
                 'xloc': '2120',
                 'yloc': '300'},
  'entry_type': 'SPECIAL',
  'filename': '',
  'is_start': False,
  'jobname': '',
  'name': 'Retry Gate',
  'transname': ''}]

HOP_DEFS = [{'enabled': True,
  'evaluation': True,
  'from_name': 'Start',
  'to_name': 'Log Job Started',
  'unconditional': True},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Log Job Started',
  'to_name': 'Initialize Variables',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Initialize Variables',
  'to_name': 'Echo Batch Context',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Echo Batch Context',
  'to_name': 'Create Log Folder',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Create Log Folder',
  'to_name': 'Create Reject Folder',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Create Reject Folder',
  'to_name': 'Create Output Folder',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Create Output Folder',
  'to_name': 'Create Archive Folder',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Create Archive Folder',
  'to_name': 'Create Audit Folder',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Create Audit Folder',
  'to_name': 'Folders Ready',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Folders Ready',
  'to_name': 'Wait For Source Flag Optional',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Wait For Source Flag Optional',
  'to_name': 'Archive Previous Outputs',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Archive Previous Outputs',
  'to_name': 'Copy Prior Logs To Archive',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Copy Prior Logs To Archive',
  'to_name': 'Log Init Complete',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Log Init Complete',
  'to_name': 'Load Master Data',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Load Master Data',
  'to_name': 'Load Customers',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Load Customers',
  'to_name': 'Load Products',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Load Products',
  'to_name': 'Load Inventory',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Load Inventory',
  'to_name': 'Load Sales',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Load Sales',
  'to_name': 'Load Finance',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Load Finance',
  'to_name': 'Load Reporting',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Load Reporting',
  'to_name': 'Cleanup Temporary Files',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Cleanup Temporary Files',
  'to_name': 'Generate Audit Report',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Generate Audit Report',
  'to_name': 'Success Email Dummy',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Success Email Dummy',
  'to_name': 'Log Job Completed',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Log Job Completed',
  'to_name': 'Success',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Initialize Variables',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Archive Previous Outputs',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Load Master Data',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Load Customers',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Load Products',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Load Inventory',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Load Sales',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Load Finance',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Load Reporting',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Cleanup Temporary Files',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Generate Audit Report',
  'to_name': 'Log Failure',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Log Failure',
  'to_name': 'Failure Email Dummy',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Failure Email Dummy',
  'to_name': 'Abort on Failure',
  'unconditional': True},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Retry Gate',
  'to_name': 'Evaluate Retry Allowed',
  'unconditional': True},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Evaluate Retry Allowed',
  'to_name': 'Retry Delay',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Retry Delay',
  'to_name': 'Increment Retry Count',
  'unconditional': False},
 {'enabled': True,
  'evaluation': True,
  'from_name': 'Increment Retry Count',
  'to_name': 'Load Sales',
  'unconditional': False},
 {'enabled': True,
  'evaluation': False,
  'from_name': 'Evaluate Retry Allowed',
  'to_name': 'Log Failure',
  'unconditional': False}]

CHILD_JOB_REGISTRY = {'Cleanup Temporary Files': ('cleanup',
                             '${Internal.Entry.Current.Directory}/../utilities/Cleanup.kjb'),
 'Generate Audit Report': ('audit', '${Internal.Entry.Current.Directory}/../utilities/Audit.kjb'),
 'Load Customers': ('load_customer_data',
                    '${Internal.Entry.Current.Directory}/../customer/Load_Customer_Data.kjb'),
 'Load Finance': ('load_finance_data',
                  '${Internal.Entry.Current.Directory}/../finance/Load_Finance_Data.kjb'),
 'Load Inventory': ('load_inventory_data',
                    '${Internal.Entry.Current.Directory}/../inventory/Load_Inventory_Data.kjb'),
 'Load Master Data': ('load_master_data',
                      '${Internal.Entry.Current.Directory}/../master_data/Load_Master_Data.kjb'),
 'Load Products': ('load_product_data',
                   '${Internal.Entry.Current.Directory}/../product/Load_Product_Data.kjb'),
 'Load Reporting': ('load_reporting_data',
                    '${Internal.Entry.Current.Directory}/../reporting/Load_Reporting_Data.kjb'),
 'Load Sales': ('load_sales_data',
                '${Internal.Entry.Current.Directory}/../sales/Load_Sales_Data.kjb'),
 'Success Email Dummy': ('notification',
                         '${Internal.Entry.Current.Directory}/../utilities/Notification.kjb')}
